name: Heroku Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18.x]
    steps:
      - name: React Build
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - name: Heroku Deploy
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ramon-cortesfullstackbankingap" #Must be unique in Heroku
          heroku_email: "ramoncortes.varios@gmail.com"